In [1]:
import sys
sys.path.insert(0, '/storage/agrp/barakma/PileupODD')

In [2]:

%load_ext autoreload
%autoreload 2

In [3]:
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import numpy as np

from huggingface_hub import HfFileSystem
import polars as pl

fs = HfFileSystem()

number_of_files = 1
event_type = 'ttbar_pu200'
number_of_hf_repo_files= 1000
# Load particles
particles_list = []
for i in range(number_of_files):
    file_path = f"datasets/CERN/ColliderML-Release-1/data/{event_type}_particles/train-{i:05d}-of-{number_of_hf_repo_files:05d}.parquet"
    with fs.open(file_path, "rb") as f:
        particles_list.append(pl.read_parquet(f, columns=[    'event_id',
    'particle_id',
    'vertex_primary',
    'pdg_id',
    'energy',
    'px',
    'py',
    'pz',
    'vx',
    'vy',
    'vz',
    'parent_id',
]))
particles = pl.concat(particles_list)

# Load calo_hits
calo_hits_list = []
for i in range(number_of_files):
    file_path = f"datasets/CERN/ColliderML-Release-1/data/{event_type}_calo_hits/train-{i:05d}-of-{number_of_hf_repo_files:05d}.parquet"
    with fs.open(file_path, "rb") as f:
        calo_hits_list.append(pl.read_parquet(f, columns=    ['event_id',
    'detector',
    'total_energy',
    'x',
    'y',
    'z',
    'contrib_particle_ids',
    'contrib_energies'
]))
calo_hits = pl.concat(calo_hits_list)

# Load tracks
tracks_list = []
for i in range(number_of_files):
    file_path = f"datasets/CERN/ColliderML-Release-1/data/{event_type}_tracks/train-{i:05d}-of-{number_of_hf_repo_files:05d}.parquet"
    with fs.open(file_path, "rb") as f:
        tracks_list.append(pl.read_parquet(f))
tracks = pl.concat(tracks_list)

In [4]:
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import numpy as np

from huggingface_hub import HfFileSystem
import polars as pl

fs = HfFileSystem()

number_of_files = 1
event_type = 'pileup_only_pu0'
number_of_hf_repo_files= 1000
# Load particles
particles_list = []
for i in range(number_of_files):
    file_path = f"datasets/CERN/ColliderML-Release-1/data/{event_type}_particles/train-{i:05d}-of-{number_of_hf_repo_files:05d}.parquet"
    with fs.open(file_path, "rb") as f:
        particles_list.append(pl.read_parquet(f, columns=[    'event_id',
    'particle_id',
    'vertex_primary',
    'pdg_id',
    'energy',
    'px',
    'py',
    'pz',
    'vx',
    'vy',
    'vz',
    'parent_id',
]))
particlespu = pl.concat(particles_list)

# Load calo_hits
calo_hits_list = []
for i in range(number_of_files):
    file_path = f"datasets/CERN/ColliderML-Release-1/data/{event_type}_calo_hits/train-{i:05d}-of-{number_of_hf_repo_files:05d}.parquet"
    with fs.open(file_path, "rb") as f:
        calo_hits_list.append(pl.read_parquet(f, columns=    ['event_id',
    'detector',
    'total_energy',
    'x',
    'y',
    'z',
    'contrib_particle_ids',
    'contrib_energies'
]))
calo_hitspu = pl.concat(calo_hits_list)

# Load tracks
tracks_list = []
for i in range(number_of_files):
    file_path = f"datasets/CERN/ColliderML-Release-1/data/{event_type}_tracks/train-{i:05d}-of-{number_of_hf_repo_files:05d}.parquet"
    with fs.open(file_path, "rb") as f:
        tracks_list.append(pl.read_parquet(f))
trackspu = pl.concat(tracks_list)

In [5]:
calo_hits.head()

shape: (5, 8)
┌──────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ event_id ┆ detector   ┆ total_ener ┆ x          ┆ y          ┆ z         ┆ contrib_p ┆ contrib_e │
│ ---      ┆ ---        ┆ gy         ┆ ---        ┆ ---        ┆ ---       ┆ article_i ┆ nergies   │
│ u32      ┆ list[u8]   ┆ ---        ┆ list[f32]  ┆ list[f32]  ┆ list[f32] ┆ ds        ┆ ---       │
│          ┆            ┆ list[f32]  ┆            ┆            ┆           ┆ ---       ┆ list[list │
│          ┆            ┆            ┆            ┆            ┆           ┆ list[list ┆ [f32]]    │
│          ┆            ┆            ┆            ┆            ┆           ┆ [u64]]    ┆           │
╞══════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ [9, 10, …  ┆ [0.000816, ┆ [202.36615 ┆ [296.12851 ┆ [-3308.44 ┆ [[140074] ┆ [[0.00081 │
│          ┆ 12]        ┆ 0.000229,  ┆ , 142.8000 ┆ , -1333.19 ┆ 9951,     ┆ ,         ┆ 6], [0.00 │
│          ┆            ┆ … 0.00110… ┆ 03, …      ┆ 9951, …    ┆ 1071.0, … ┆ [176808], ┆ 0229], …  │
│          ┆            ┆            ┆ -426…      ┆ -3…        ┆ -3698…    ┆ …         ┆ [0.…      │
│          ┆            ┆            ┆            ┆            ┆           ┆ [101665…  ┆           │
│ 1        ┆ [11, 11, … ┆ [0.000176, ┆ [-81.59999 ┆ [979.78894 ┆ [3399.350 ┆ [[63413], ┆ [[0.00017 │
│          ┆ 10]        ┆ 0.000072,  ┆ 8, -306.94 ┆ , -343.009 ┆ 098, 3293 ┆ [37771],  ┆ 6], [0.00 │
│          ┆            ┆ … 0.00005… ┆ 7235, …    ┆ 705, …     ┆ .300049,  ┆ …         ┆ 0072], …  │
│          ┆            ┆            ┆ 28…        ┆ 126…       ┆ … 2…      ┆ [144414]] ┆ [0.…      │
│ 2        ┆ [11, 9, …  ┆ [0.000157, ┆ [449.38894 ┆ [56.099998 ┆ [3389.25, ┆ [[163748] ┆ [[0.00015 │
│          ┆ 9]         ┆ 0.001176,  ┆ 7, -1191.7 ┆ , 256.2647 ┆ -3257.949 ┆ ,         ┆ 7], [0.00 │
│          ┆            ┆ … 0.00428… ┆ 36206, …   ┆ 09, …      ┆ 951, …    ┆ [104990,  ┆ 0945,     │
│          ┆            ┆            ┆ -…         ┆ 458.…      ┆ -323…     ┆ 104993],  ┆ 0.0002…   │
│          ┆            ┆            ┆            ┆            ┆           ┆ ……        ┆           │
│ 3        ┆ [11, 10, … ┆ [0.000953, ┆ [174.84870 ┆ [-728.6417 ┆ [3222.600 ┆ [[169741, ┆ [[0.00078 │
│          ┆ 11]        ┆ 0.000507,  ┆ 9, 820.349 ┆ 85, 1015.0 ┆ 098, 3014 ┆ 169742],  ┆ 7, 0.0001 │
│          ┆            ┆ … 0.00015… ┆ 915, …     ┆ 87158, …   ┆ .100098,  ┆ [126776], ┆ 66],      │
│          ┆            ┆            ┆ 119…       ┆ -…         ┆ … 3…      ┆ ……        ┆ [0.0005…  │
│ 4        ┆ [11, 9, …  ┆ [0.000799, ┆ [119.86666 ┆ [-569.2495 ┆ [3263.0,  ┆ [[120679, ┆ [[0.00062 │
│          ┆ 9]         ┆ 0.000682,  ┆ 1, 685.602 ┆ 12, 736.09 ┆ -3247.850 ┆ 183561],  ┆ 9,        │
│          ┆            ┆ … 0.00012… ┆ 905, …     ┆ 0332, …    ┆ 098, …    ┆ [212636], ┆ 0.00017], │
│          ┆            ┆            ┆ -34…       ┆ -3…        ┆ -3207…    ┆ ……        ┆ [0.00068… │
└──────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┘

In [6]:
(calo_hitspu
 .select('x', 'y', 'z')
 .explode('x', 'y', 'z')
 .filter((pl.col('x')== 202.36615) & (pl.col('y')== 296.12851) & (pl.col('z')== -3308.449951))
 )

shape: (12, 3)
┌───────────┬───────────┬──────────────┐
│ x         ┆ y         ┆ z            │
│ ---       ┆ ---       ┆ ---          │
│ f32       ┆ f32       ┆ f32          │
╞═══════════╪═══════════╪══════════════╡
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ …         ┆ …         ┆ …            │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
└───────────┴───────────┴──────────────┘

In [ ]:
(calo_hitspu
 .select('x', 'y', 'z')
 .explode('x', 'y', 'z')
 .filter((pl.col('x')== 202.36615) & (pl.col('y')== 296.12851) & (pl.col('z')== -3308.449951))
 )

In [ ]:
(calo_hitspu
 .select('x', 'y', 'z')
 .explode('x', 'y', 'z')
 .
 .filter()
 )

shape: (12, 3)
┌───────────┬───────────┬──────────────┐
│ x         ┆ y         ┆ z            │
│ ---       ┆ ---       ┆ ---          │
│ f32       ┆ f32       ┆ f32          │
╞═══════════╪═══════════╪══════════════╡
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ …         ┆ …         ┆ …            │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
│ 202.36615 ┆ 296.12851 ┆ -3308.449951 │
└───────────┴───────────┴──────────────┘